# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ecd240f839a16d6b3c426e66e13e167c1fe7a58180d04cdf2fca10be54a1a839f2a5f66aea35fccd3a87516e452c811c08d5fdff56302610ede7e447ab54c57

test:
  secret_key_base: 1beb4c426690c9a89c4aa8c2690c29b6f08040394d863b651543758195f040bd1f3a4f6f635f0b035fcf316490ee1c45b38d0d35434ce5e5fecbd46400f3a206

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
